### ISSUE TITLE
New Screen Options window

### ISSUE THREAD

**Issue by vitor251093** [vitor251093/wineskin#12]
Something that would be really helpful is a change in the Screen Options window, in order to separate in more proper groups and categories.

-> (X11 / Mac Driver) & (Auto-detect GPU) & (Direct3D Boost) & (Gamma)
-> X11 -> (Automatic / Override) & (Color Depth)
-> X11 -> Override -> (Virtual Desktop / Normal Windows) & (Decorate Windows) & (Installer Options)
-> X11 -> Override -> Virtual Desktop -> (Fullscreen / Windowed) & (Resolution)

That would be a division which is closer to reality, and which only show/enable options when they are functional in a specific order. It would even open space to add more Mac Driver options, like the Retina Mode.

Switch Pause isn't used by the WineskinLauncher anymore.

**Comment by Gcenx** [comment]
I agree changing the screen options menu would be better than trying to get it working the way we have been up till now

**Comment by vitor251093** [comment]
New print of the window, this time with the alignment adjusts, minor changes, and with the window working instead of an Interface Builder print.

<img width="804" alt="screen shot 2018-04-15 at 20 41 21" src="https://user-images.githubusercontent.com/8976483/38784781-75ec5a30-40ed-11e8-9e2d-35da4f5cb73c.png">

**Comment by Gcenx** [comment]
That looks really good.

I was thinking of rolling the screen options into a tab of the advanced widow but then it causes space constraints unless it auto expands to accommodate the options. Then roll in the Quartz tickbox and the force wrapper quartz-wm into the menu but it didn't seem to fit.

Only weird thing to me is the large done button seems out of place, but that's minor.

**Comment by Gcenx** [comment]
How is this screen replacement going?

**Comment by vitor251093** [comment]
It's already working. However I didn't had time to upload, and I was waiting for more suggestions. Maybe someone has an idea of how to 'fix' the large Done button :)

**Comment by Gcenx** [comment]
I guessed you have been busy.

Just put it to the right normal sized like the original, the large button just seems weird as hell with text in the middle but the rest like I said look great.

**Comment by Gcenx** [comment]
It happens, all I have been doing was trying bug hunting the Launcher when I had free time.
So far I like the changes to Screen options, yeah removing that done button might be for the best.

**Comment by Gcenx** [comment]
OK I decided to look at RetinaMode and it would need more options added to make it viable

<img width="405" alt="screen shot 2018-05-17 at 9 52 48 am" src="https://user-images.githubusercontent.com/38226388/40181916-3cbe520c-59b8-11e8-994d-440fae5cbc8d.png">
That is using RetinaMode and DPI scaling to 200 as you can see.

The current DPI rendering is still how WinXP would handle it, big display make everything small, so for it to be viable it would also need DPI control for Wine possibly with a preview like the one built into winecfg.

Without scaling this is the winecfg windows, I'm running a Macbook Pro13 mid 2014, so im sure it would be worse on a larger display and almost nothing on a 5K display.
<img width="202" alt="screen shot 2018-05-17 at 9 57 43 am" src="https://user-images.githubusercontent.com/38226388/40182153-c5e96b52-59b8-11e8-9823-04f01c84b0a2.png">

**Comment by vitor251093** [comment]
Alright, then we can change that value ;)

There is a function in ObjectiveC_Extension (retinaScale) that returns a floating point value that correspond to the screen rate change caused by dpi. To solve that issue, we would just need to set that value to 96*retinaScale. It would adapt itself to any screen dpi.

**Comment by vitor251093** [comment]
Alright, the Retina Mode button was added and is working :)

Also, I've removed the Done button like we discussed.
