### ISSUE TITLE
debug.log on desktop after each run?

### ISSUE THREAD

**Issue by Gcenx** [vitor251093/wineskin#15]
I might have missed something, but when ever launched I find a debug.log on the desktop did I miss something as I don't remember this happening at first.

**Comment by vitor251093** [comment]
That's due to the ObjectiveC_Extension `NSDebugLog`. I was using while developing those contents on PK. It's a log that's only generated while the app is in Debug mode, which is the case when you run it through Xcode without archiving. I will remove the two logs that are creating that file.

**Comment by vitor251093** [comment]
Done. The problem should be gone in the WineskinLauncher. WineskinApp probably still have some, but that one can be archived with no problems.
