### ISSUE TITLE
Winetricks installation should be silent, Not working

### ISSUE THREAD

**Issue by Gcenx** [vitor251093/wineskin#17]
Winetricks runs the same as before with normal install windows.

Unlike Porting kit, I'm guessing the feature is meant to be working like Porting Kit's where winetricks is run silently without needing user input?

**Comment by vitor251093** [comment]
Well, I haven't added that feature specifically to Wineskin because sometimes you may really want to test the installation of a winetrick in non-silent mode (even in PK some winetricks are marked as exceptions, running in non-silent mode, because in silent mode they are buggy).

However, it would be interesting to add that feature to Wineskin. Although, in order to be properly implemented, and not a workaround like I did in PK, the best would be to support a "-silent" flag in WineskinLauncher while installing winetricks, so we can use that flag in the WineskinApp. Today, PK modified the winetricks file to use the silent mode, even though WineskinLauncher asks it to install in regular mode.

**Comment by Gcenx** [comment]
Oh I got the impresseion it was added or going to be added due to what the readme says (that's why I used that as the title)

Hum that sounds interesting;
My idea would be to run "-silent" normally but when running debugmode that is disabled

**Comment by vitor251093** [comment]
Well, running the port in Debug mode and installing winetricks are separated things.

I imagined a "Silent mode" checkbox in the Winetricks window, so they user can choose using the silent mode or not. It would be checked by default to save time, of course ;)

**Comment by Gcenx** [comment]
That is a much better option, I forgot debug mode is another thing entirely ;(

**Comment by vitor251093** [comment]
Which is the specific change that this checkbox makes? No logs or no windows?

**Comment by Gcenx** [comment]
Both really, no Windows and no Winedebug information.

<img width="797" alt="screen shot 2018-05-14 at 4 07 20 pm" src="https://user-images.githubusercontent.com/38226388/40020771-ec8a0322-5790-11e8-937e-a7ec51bb51cf.png">

So instead of getting all the wine:error, wine:fixme
When it's enabled those are not shown and along with "winetricks -q" being applied 

When its disabled Winetricks runs normal including the normal wine:error/wine:fixme output

**Comment by Gcenx** [comment]
Ok sounds like a good idea I will change the checkbox to do that.
Now the placement for "silent mode"

Maybe I could move over the "Custom" checkbox and the hidden text filed a little and add it their


What do you think about keeping the "Warning" message if Silentmode is enabled "Winetricks" button is pressed if its enabled?

**Comment by Gcenx** [comment]
I updated the "Advanced" window now 
<img width="675" alt="screen shot 2018-05-14 at 8 48 09 pm" src="https://user-images.githubusercontent.com/38226388/40030370-35f8922c-57b8-11e8-9be0-3afcfd605cc0.png">

Now here is the Silent checkbox in Winetricks
<img width="796" alt="screen shot 2018-05-14 at 8 46 35 pm" src="https://user-images.githubusercontent.com/38226388/40030387-474f8a12-57b8-11e8-9bd0-4436eaed4e12.png">

And when "Custom..." is checkbox is enabled
<img width="794" alt="screen shot 2018-05-14 at 8 46 45 pm" src="https://user-images.githubusercontent.com/38226388/40030405-648c0362-57b8-11e8-8459-c32a1e10dd69.png">

For the last thing, I was thinking of changing the warning from being about "Winetricks Silent Mode"
To waring about the disabled winelogs.

**Comment by Gcenx** [comment]
Thanks,

Any idea for the warning message?, - I was thinking of keeping it linked to inform about Silent mode, but inform the user about it.
But I keep coming blanking on how to keep it short but descriptive ;|

**Comment by Gcenx** [comment]
I'm still new to this so I'm not even sure where I would start add that, but "-silent" does sound preferable.

**Comment by vitor251093** [comment]
Don't worry, I can do that ;)

I just need some spare time to work on that.
