### ISSUE TITLE
Add Travis-CI 

### ISSUE THREAD

**Issue by chrisballinger** [vitor251093/wineskin#20]
If you enable the repo on https://travis-ci.org/ I can contribute a `.travis.yml` file. In addition to ensuring build are not accidentally broken, we can use it to automatically build and host debug builds.

**Comment by vitor251093** [comment]
Just enabled it ;)

**Comment by chrisballinger** [comment]
Nice! I'm also tracking Travis support over here in the Wineskin Community fork: https://github.com/WineskinCommunity/Wineskin/issues/4
