### ISSUE TITLE
WineskinX11 is outdated - removal?

### ISSUE THREAD

**Issue by Gcenx** [vitor251093/wineskin#24]
Since WineskinX11 is a very old custom version of XQuartz why not just remove it?

Currently creating a new wrappers launches WineskinX11 but that is not needed anymore Wine2.0 had a stable Mac driver and is used by default since then.
Removing would help future updates to Wineskin. Instead of needing to make a new version (+patches etc) have the user required to install xorg from homebrew/macports if they really need X11 support.

Doing so would have have another useful benefit; needing less dylibs inside the master wrapper, so less of a headache with needing to update them to work with every system 10.6 > 10.13. I would would go as far as change the minimal requirement of Wineskin to 10.8+

**Comment by vitor251093** [comment]
> Since WineskinX11 is a very old custom version of XQuartz why not just remove it?
> 
> Currently creating a new wrappers launches WineskinX11 but that is not needed anymore Wine2.0 had a stable Mac driver and is used by default since then.
> Removing would help future updates to Wineskin. Instead of needing to make a new version (+patches etc) have the user required to install xorg from homebrew/macports if they really need X11 support.
> 
> Doing so would have have another useful benefit; needing less dylibs inside the master wrapper, so less of a headache with needing to update them to work with every system 10.6 > 10.13.

I agree that we shouldn't give priority to WineskinX11, even because XQuartz is here. 

At first I thought that we should keep it, but you are right... it's just waste, specially because macOS 10.14 won't have 32 bit support, which means that we gonna need lots of extra work to make it functional.

XQuartz should still be supported in case people want to use it in macOS versions older than 10.14, but WineskinX11 may go.

> I would go as far as change the minimal requirement of Wineskin to 10.8+

If the latest version of some dylib require 10.8+ to work without tweaks, then yes. Otherwise, there isn't much need to do that _at this moment_ (the time to do that will certainly come, sooner or later). Wineskin itself has no need of any 10.7+ only resource for now, as far as I know.

**Comment by Gcenx** [comment]
>At first I thought that we should keep it, but you are right... it's just waste, specially because macOS 10.14 won't have 32 bit support, which means that we gonna need lots of extra work to make it functional.

Exactly what I was thinking I'm even having issues now due to needing to juggle dependancies just to keep WineskinX11 working and that's on 10.13.

I wouldn't even recommend XQuartz 2.7.8+ anymore to be honest it includes a broken freetype version pixelated fonts anyone? Better to recommend an port from homebrew/macports like I said before since those are maintained and include newer dylibs and saves anyone here needing to worry about keeping it functional. (Crossover includes its own freetype/png/jpeg dylibs to combat that)

>If the latest version of some dylib require 10.8+ to work without tweaks, then yes. Otherwise, there isn't much need to do that at this moment (the time to do that will certainly come, sooner or later). Wineskin itself has no need of any 10.7+ only resource for now (as far as I know at least).

All official builds from Winehq require 10.8 and Staging do include some prebuild dylibs inside that are 10.8 only, Crossover source wouldn't even compile with anything lower then 10.9SDK.

To get it working below 10.8 would be a pain _(need to include system dylibs from 10.8+)_ I had someone test for me using the provided dylibs from my unofficial update and it crashed that system (OSX 10.6.8 same with 10.7)

**Comment by vitor251093** [comment]
> All official builds from Winehq require 10.8 and Staging do include some prebuild dylibs inside that are 10.8 only, Crossover source wouldn't even compile with anything lower then 10.9SDK.
> 
> To get it working below 10.8 would be a pain (need to include system dylibs from 10.8+) I had someone test for me using the provided dylibs from my unofficial update and it crashed that system (OSX 10.6.8 same with 10.7)

Gijs was helping us in the Porting Kit to make the recent engines compatible with macOS 10.6 and 10.7.  Indeed, it's a hard task. However, Wineskin itself can work with older engines with users of older systems. As soon as it isn't a problem for us while programming Wineskin, WineskinLauncher or Wineskin Winery, then we can still keep it that way for them. At least in our first release, so they can have an stable version of the updated Wineskin.

**Comment by Gcenx** [comment]
So custom compiled engines with a different "Frameworks folder for 10.6/10.7" and lock to 32bit only engines.

Then 10.8+ use what we consider the "Normal Frameworks Folder" with newer libs and 64bit engine support.

**Comment by Gcenx** [comment]
Are you sure? The new libs needed for those new engines didn't work on 10.6.8 when I had someone testing for me

With the old versions they could use it like normal, that's why I mention it

**Comment by vitor251093** [comment]
Well, we can try then. But let's not give high priority to that.

I will start a new issue to give focus to that.

**Comment by vitor251093** [comment]
https://github.com/vitor251093/wineskin/issues/25
