### ISSUE TITLE
Frameworks for 10.6-10.7 engines and 10.8+ engines

### ISSUE THREAD

**Issue by vitor251093** [vitor251093/wineskin#25]
In order to support 10.6 and 10.7 systems, there needs to be a separated Frameworks folder (so basically, a different master wrapper) for those systems.

**Comment by Gcenx** [comment]
We can just use the Frameworks from 2.6.2 and leave it alone, that way we won't break anything.

Once X11 is removed we can scrap most of the Frameworks dylibs and use actual updated ones since we don't need to worry about maintaining compatibility between WineskinX11 and newer dylibs

**Comment by vitor251093** [comment]
Uhn, makes sense.

**Comment by chrisballinger** [comment]
If I were to vote I'd say drop support for anything under 10.8 and possibly even 10.10.
