### ISSUE TITLE
Screen options - issues.

### ISSUE THREAD

**Issue by Gcenx** [vitor251093/wineskin#26]
Sometimes when swapping between MAC/X11 is does not save the selection so it needs to be done over. (related to the removal of the Done button I guess?)

"Retina Mode"
Should not be enable by default, its great for some applications but some Windows applications have the scaling issue, this is not text related since the scaling factor is still based on Windows XP scaling system not all applications will scale up looking tiny even with the font scaling you implemented.

EDIT:
It even changed my driver from MAC to X11 on another test thats weird....

**Comment by vitor251093** [comment]
> Sometimes when swapping between MAC/X11 is does not save the selection so it needs to be done over. (related to the removal of the Done button I guess?)

I guess the problem is the difference in the behaviour. I've changed it to save only when the window is closed. Probably that's what causing the issue. I will change that.

> Should not be enable by default, its great for some applications but some Windows applications have the scaling issue, this is not text related since the scaling factor is still based on Windows XP scaling system not all applications will scale up looking tiny even with the font scaling you implemented.

My mistake. It isn't enabled by default, it just isn't loading :P 

> It even changed my driver from MAC to X11 on another test thats weird....

That's really weird, but it's probably related with the first bug.

**Comment by vitor251093** [comment]
Fixed both problems. It should be working correctly now.

Also, from now on I will make my changes pull requests, so they can be tested before being merged as well. Those pushes directly to the master have proved to be a potential problem :P

**Comment by Gcenx** [comment]
Cool, 

>Also, from now on I will make my changes pull requests, so they can be tested before being merged as well. Those pushes directly to the master have proved to be a potential problem :P

Or use a Testing Branch and we can test that out before merging them fully

**Comment by Gcenx** [comment]
Lol, I managed to break it again already ;D

Enable "Retina Mode" then swap to X11 and boom huge ass window

**Comment by vitor251093** [comment]
Whops, my bad :P 

Fixed it.

**Comment by vitor251093** [comment]
> Or use a Testing Branch and we can test that out before merging them fully

Makes more sense.

**Comment by chrisballinger** [comment]
You may want to try to adopt "git flow": https://nvie.com/posts/a-successful-git-branching-model/

**Comment by Gcenx** [comment]
That does seem nice.

That seems to have fixed it now, so closing
