### ISSUE TITLE
Default reg entries are not written on wrapper creation

### ISSUE THREAD

**Issue by Gcenx** [vitor251093/wineskin#3]
When making a new wrapper, the default reg entries are not imported into the wrapper

Also when changing settings later via WineSkin or even winetricks to change from MAC to X11 the reg changes do not get saved

Even entering them manually via regedit entries are not saved

**Comment by vitor251093** [comment]
> When making a new wrapper, the default reg entries are not imported into the wrapper

A mistake of mine indeed. When I split the command into an array, I forgot to add ` 2>&1` to the end of the last line. I will fix that.

> Also when changing settings later via WineSkin or even winetricks to change from MAC to X11 the reg changes do not get saved
> Even entering them manually via regedit entries are not saved

I will check that as well. Maybe it's been cause by the the prior mentioned bug, but may also be a separated bug.

**Comment by vitor251093** [comment]
Fixed the first mentioned bug. Could you please check if the second one was solved by that as well?

**Comment by Gcenx** [comment]
I'm not sure what's going on, I checked the user.reg and the x11 entries are now their but wineskin still launches using MAC driver instead of the default X11

Then launched regedit and the does not show these entries. But I copied over user.reg from another wrapper that already had X11 set and then it launched in X11 mode and when I changed it over to MAC it launched and back to X11 and it worked fine...

**Comment by Gcenx** [comment]
<img width="1280" alt="screen shot 2018-04-10 at 2 05 19 pm" src="https://user-images.githubusercontent.com/38226388/38575076-774bb052-3cc8-11e8-966c-084af10f6c33.png">

Seem's its all to do with how your writing the regfiles

The one on the left is from a working wrapper using X11 

The one on the Right is using the code right after creation

**Comment by vitor251093** [comment]
Fixed it. It was probably during my tries of minimising the code. 

I will make some tests on my side as well to be sure that there are no other bugs of that kind.
