### ISSUE TITLE
Remove Graphics=x11 from remakedefaults.reg

### ISSUE THREAD

**Issue by vitor251093** [vitor251093/wineskin#37]
Since Mac Driver is used most of the time, and Wine uses Mac Driver by default since 1.5.28, we can remove that line so Wine can decide which one it's going to use. In that way, X11-only compatible engines will still work, and Mac Driver compatible engines will give a preference to it.

**Comment by Gcenx** [comment]
> Since Mac Driver is used most of the time, and Wine uses Mac Driver by default since 1.5.28, we can remove that line so Wine can decide which one it's going to use. In that way, X11-only compatible engines will still work, and Mac Driver compatible engines will give a preference to it.

Well currently we use that string to check what driver is currently in use, we could just swap it to say "Mac" 

But then launching older engines that don't support mac driver need that set to X11 of XQuartz won't launch. Might need to do some more changes to my next pull-request.

**Comment by vitor251093** [comment]
We can also use "mac,x11" instead. It gives preference to "mac", and if it's not present it uses "x11".

**Comment by vitor251093** [comment]
I shouldn't have free time to do until Wednesday, so whoever gets free time first do it I guess ;P

By the way, I just added you has a collaborator to the project. In that way, you have more power over the branches, and don't need to wait until I have free time to answer or to do anything.

Oh, also, I forgot to say: I have a Mac Developer account, so the Wineskin Winery and the WineskinApp releases can be code-signed :) That just can't be done with WineskinLauncher, because once an app is code-signed, it's Info.plist file can't be modified, otherwise the app won't launch in the latest macOS versions.

**Comment by Gcenx** [comment]
> I shouldn't have free time to do until Wednesday, so whoever gets free time first do it I guess ;P

I'm busy all next week the other guy at work is off so i'm solo.

> By the way, I just added you has a collaborator to the project. In that way, you have more power over the branches, and don't need to wait until I have free time to answer or to do anything.

Thanks that could come in handy later down the line for bug fixes.

> Oh, also, I forgot to say: I have a Mac Developer account, so the Wineskin Winery and the WineskinApp releases can be code-signed :) That just can't be done with WineskinLauncher, because once an app is code-signed, it's Info.plist file can't be modified, otherwise the app won't launch in the latest macOS versions.

Yeah I figured since you Signed PK. Stupid question on code-signed applications is it only broken if you change the plist or if you change anything inside the application?

**Comment by vitor251093** [comment]
> Yeah I figured since you Signed PK. Stupid question on code-signed applications is it only broken if you change the plist or if you change anything inside the application?

Being sincere, I'm not sure. I'm absolutely sure about the Info.plist file (tried so code-sign WineskinLauncher once), but not about the 'Resources', the 'Frameworks' or the 'MacOS' folders. It's difficult to confirm based in older experiments because some things have changed regarding to that in the later years.

I think the WineskinLauncher can be manually signed in a finished port without X11 related files, but haven't tested that either.

**Comment by vitor251093** [comment]
> I was wondering since if any change inside the Master Wrapper could break the signature then we should consider moving Winetricks outside of “Wineskin.app”

It could even be inside the `~/Library/Application Support/Wineskin` I think. Since it isn't really needed for using the wrapper, but it's to create it.

> I don’t think it matters since I did sign WineskinLauncher and moved it into my wrapper and didn’t get any issues using unlike Wineskin-2.6.2

I had the exact opposite problem xD

I could sign the Wineskin App and use it inside a port, but I couldn't use a signed WineskinLauncher. How did you signed them both? I've signed the Wineskin App using Xcode's Archive option.

**Comment by Gcenx** [comment]
Then maybe should move winetricks there then we don’t need to worry about what version of winetricks someone has it’s always current and no need to update each wrapper to the current version.

I debug Signed WineskinLauncher but do the same as you for Wineskin.app

Nobody complained using “unofficial update” both the manual version the edited winery.app version.


Also might as well merge this then the updates readme, then we can worry about the other changes for the stable release. So you agree?

**Comment by vitor251093** [comment]
> Also might as well merge this then the updates readme, then we can worry about the other changes for the stable release. So you agree?

Sounds good for me.

> I still didn’t add a size check for 7z change I just remembered.

Size check?

**Comment by Gcenx** [comment]
> Uhn, got it. Good idea. Still, wouldn't be more safe to use a hash instead, like winetricks does? Like sha256 for example?

I forgot all about using hash checking.... Yeah that's much better.

**Comment by Gcenx** [comment]
Well I can pickup my Mac & Apple Watch today so I will take care of the things discussed in this issue.

**Comment by vitor251093** [comment]
Don't worry, solved it already (the 7za hash thing at least) :)

Sorry for not doing it yesterday, but I was very tired in the end of the day.

**Comment by Gcenx** [comment]
@vitor251093 don't worry about it.

You did the part I was hoping you would take care of (7za part), I got the mac,x11 changes including Wineskin.app etc when im done I will upload my changes

**Comment by Gcenx** [comment]
This issues is closed as the needed changes were implemented into;
Wineskin.app / WineskinLauncher & Winery.app
