### ISSUE TITLE
Virtual Desktop is affected by the reg bug from before

### ISSUE THREAD

**Issue by Gcenx** [vitor251093/wineskin#4]
After doing some changes to the WineSkin.app I noticed that VirtualDesktop is suffering from the bug that caused the reg issue before 
<img width="637" alt="screen shot 2018-04-11 at 2 29 46 pm" src="https://user-images.githubusercontent.com/38226388/38636041-221e3af0-3d95-11e8-984d-ff73c0e74bf1.png">

**Comment by vitor251093** [comment]
Fixed it. It happened due to a difference between the Wineskin method to add registries and mines, which is used in PK. Basically I ended up adding doubled quotes by mistake.

It wasn't exactly the same bug than before, but indeed, it was bug in the registry :)
