### ISSUE TITLE
Project modernization

### ISSUE THREAD

**Issue by galijot** [vitor251093/wineskin#53]
Thank you very much for maintaining this project!

I would like to contribute, if the following proposal would work and is acceptable by the maintainers.

Before I start, I'd like to ask about something that's been bugging me. I've found quite a few repositories related to wineskin, and I'm not sure what are their purposes? This repo, to me it seems, is "the main" repo, containing project's source code; is it? Other repos could be found at https://github.com/Gcenx?tab=repositories, though there's also https://github.com/The-Wineskin-Project with many wineskin-related repos. I'd appreciate if someone could clarify 🙏

Additionally, there are many stale branches in this repo. As of this writing, it seems the most up-to-date active branch is `Unoffical_Wineskin`. Is there a reason for keeping other branches?

I'm not familiar with how wine works, and I haven't explored this project in detail to learn the magic of how it integrates wine and how things work in general. Though I have experience developing for Apple platforms, and am experienced with Objective-C and Swift.
I have analyzed the project and found quite a few issues with it; deprecated method usages, main thread blocking with long running operations, etc.
I would like to list some things I've found that I believe would be great to resolve. My ultimate goal is modernizing the project and keeping it up to date, by which I mean potentially moving to Swift, and one day, who knows, maybe SwiftUI for UI. I'm eager to hear what others think.

Before I continue: I haven't even been able to successfully run all the apps in this project (I did some, but had to resolve some compilation issues), but I was so hyped about improving it that I wanted to create this issue. I'd obviously need help from experienced maintainers during this process, foremost to learn about the internals.

* ObjectiveC-Extensions
    * This is the only library installed through a dependency manager, and if I'm not mistaken, there are many things in it that either aren't needed anymore or aren't used. The library itself has many warnings which would have to be resolved, and if such a large refactor would be done, it would be much easier if this library is directly inside of the project. That way we can slowly start removing things that aren't used, and stripping the library down to only the things that are needed for Wineskin.
* Project groups and folders
    * Xcode project's files are grouped into groups, but those groups don't represent folders on the filesystem. For example, Wineskin project's `Classes`, `Model`, `Functions` and `Views`, they're all shown as groups in Xcode but those groups don't have their corresponding folders on the filesystem. I would like to change that so that it's much easier to do code review and navigate through files in GitHub repo. As we move forward, I'd propose a different folder structure, based on how we end up organizing everything.

These are some of the things I'd want to start with. I won't be listing many of the warnings about deprecated API usages, but those too are something I aim at solving. I also care very much about UI, so if we proceed with this, I'd be happy to revisit that one day as I've found there are many warnings in XIP files too (like missing constraints).

Let me know what you think @vitor251093 @Gcenx

**Comment by Gcenx** [comment]
I've published the current sources to https://github.com/The-Wineskin-Project/wineskin-source

**Comment by Gcenx** [comment]
@galijot some of the issues you’ve mentioned were lightly resolved already, at least the mai thread blocking was resolved, possibly others.

ObjectiveC-Extensions will just become a subproject instead of requiring a package manager.

Moving everything around to more match what’s shown within Xcode makes sense pretty sure I didn’t complete this.

As long as the project continues to function on macOS Catalina and later I’d more or less be happy.

<br>

I’m targeting macOS Catalina still as that’s what we’re also targeting for Winehq as I’m the official macOS Winehq package maintainer.

**Comment by Gcenx** [comment]
@galijot pretty much the currently active Wineskin tail fork is completely moving to https://github.com/The-Wineskin-Project this will include WineskinSever eventually.

**Comment by galijot** [comment]
Thanks @Gcenx!

Yes, I'd move ObjectiveC-Extensions as a subproject, but the goal would be to preserve only the things that are used and remove what isn't.

Sounds good!

I'll be attempting the first step (ObjectiveC-Extensions migration) in a couple of days.

**Comment by galijot** [comment]
Sorry about the delay. I put up my first PR here: https://github.com/The-Wineskin-Project/wineskin-source/pull/2

I think we could close this issue. What do you think @Gcenx?

**Comment by galijot** [comment]
I'll close this issue since this work already started. I'll continue making updates in https://github.com/the-wineskin-project/wineskin-source
